- name: Docker
  hosts: 127.0.0.1
  connection: local
  tags: docker
  tasks:

  - name: Install Docker dependencies
    apt: name="{{package}}" state=present
    vars:
      package:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-pip
    become: true

  - name: Remove legacy Docker packages
    apt:
      name: "{{package}}"
      purge: yes
      state: absent
    vars:
      package:
      - lxc-docker
      - docker
      - docker-engine
    become: true

  - name: Add Docker APT repository key
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
    become: true

  - name: Get upstream codename (bionic, xenial, trusty etc.)
    shell: >
      lsb_release -cus ; lsb_release -cs
    changed_when: false
    register: upstream_codename

  - name: Add Docker APT repository
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu {{ upstream_codename.stdout_lines[0] }} stable"
      state: present
    become: true

  - name: Install Docker
    apt:
      name: docker-ce
      state: present
    become: true

  - name: Ensure group "docker" exists
    group:
      name: docker
      state: present
    become: true

  - name: Adding existing user {{ ansible_user_id }} to group docker (to run docker without sudo)
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    become: true

  - name: Install docker-compose
    pip:
      name: docker-compose
    become: true
